# SITE CONFIGURATION
baseurl: ""
url: "https://blog.jujinkim.com"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Blog.JujinKim.com
  avatar: 
  favicon: assets/favicon.ico
  gravatar: b29ffe51445057ea65f5a687e8a2ac63
  description: "Jujin Kim's weblog. Welcome to OhRockInJourneyStudio" # used by search engines

  # Header and footer text
  header_text: Blog.JujinKim.com
  header_text_feature_image:
  footer_text: >
    Copyright 2018, Jujin Kim from OhRockInJourney | Powered by GithubPage&<a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: true
  email_address: jk012345@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "jujinkim"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/jujinkim
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "twitter"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-54002449-5 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: blog-jujinkim-com
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock

